version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      # checkout : GitHubからCircleCIの環境にソースコードをコピー
      - checkout
      # CircleCIの環境にcomposerとかをインストールする
      - run: sudo composer self-update --1

      # 保存されたキャッシュを復元する。keyには、復元するキャッシュの名前を指定
      - restore_cache:
          key: composer-v1-{{ checksum "composer.lock" }}

      - run: composer install -n --prefer-dist

      # keyに指定した名前でキャッシュを保存。パッケージをキャッシュ(記憶)しておいてビルドを早くする
      - save_cache:
        # checksumはCircleCIのテンプレート機能。{{ checksum "ファイル名" }}とすることで、ファイルをハッシュ化した値を算出
        key: composer-v1-{{ checksum "composer.lock" }}
        # 保存するディレクトリ名やファイル名はpathsへ記述
        paths:
        - vendor

      - run: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit

  # composer.lockに変更が無い限りは、restore_chacheでは「前回以前のCircleCI実行時のsave_cacheで保存されたキャッシュ」を復元する
  # composer.lockに何か変更があれば、restore_chacheではキャッシュを復元せず、save_cacheで新しいkeyにてキャッシュを保存し直す