version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      # checkout : GitHubからCircleCIの環境にソースコードをコピー
      - checkout
      # CircleCIの環境にcomposerとかをインストールする
      - run: sudo composer self-update --1
      - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit